### ISSUE TITLE
Reinjecting the workspace with obscured shadow blocks throws an exception

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#204]
When the workspace is reinjected, by e.g. changing the language or theme, and an obscured shadow block exists on the workspace, the following stack trace is emitted:

minilog.js:17 gui  TypeError: Workspace Update Error: Shadow block cannot be a top-level block.
    at Vo.domToWorkspace$$module$build$src$core$xml (main.js:1:1)
    at Object.eO [as clearWorkspaceAndLoadFromXml] (main.js:1:1)
    at Blocks.onWorkspaceUpdate (blocks.jsx:523:1)
    at VirtualMachine.wrapper (index.js:550:1)
    at VirtualMachine.emit (events.js:153:1)
    at VirtualMachine.emitWorkspaceUpdate (virtual-machine.js:1416:1)
    at VirtualMachine.refreshWorkspace (virtual-machine.js:1329:1)
    at blocks.jsx:301:1

**Comment by plabanTest1** [comment]
![image](https://github.com/user-attachments/assets/e0f494f1-ec27-4ba4-9f4f-14af65643c01)

![image](https://github.com/user-attachments/assets/75628ab6-6f21-442b-b509-6030b64a7e0d)
