### ISSUE TITLE
Reinjecting the workspace with a variable getter block inside another block throws an exception

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#210]
When a variable getter block is inside of another block on the workspace, and the workspace is reinjected by e.g. changing the language or theme, the following exception is thrown:

main.js:1 Uncaught TypeError: Cannot create a rendered block in a headless workspace
at new ES (main.js:1:1)
at cS.newBlock (main.js:1:1)
at jt (main.js:1:1)
at zt (main.js:1:1)
at jN.createShadowBlock (main.js:1:1)
at jN.respawnShadow_ (main.js:1:1)
at jN.respawnShadow_ (main.js:1:1)
at jN.disconnectInternal (main.js:1:1)
at jN.disconnectInternal (main.js:1:1)
at jN.disconnect (main.js:1:1)

**Comment by plabanTest1** [comment]
Not throwing any exception when changing language or theme/contrast.

![image](https://github.com/user-attachments/assets/a3a43134-c38a-434f-b02e-b75e0da687c0)
![image](https://github.com/user-attachments/assets/eba378ef-8650-40da-b49d-f015568f07b5)
![image](https://github.com/user-attachments/assets/fb33f27a-8e5d-49a7-a179-d09200e9fa9f)
